# Generated by Django 3.0.8 on 2020-07-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Username',
        ),
        migrations.AddField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Message',
            field=models.TextField(default='None'),
        ),
    ]
